name: Deploy resource using Cloudformation stacks

on: push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Install dependencies
      run: pip install awscli cfn-lint
    - name: Validate & lint template
      run: |
        ls -laht
        git diff --name-only HEAD~1..HEAD | grep 'template.yaml' | while read line; do
          DIR=$(dirname "$line")
          aws cloudformation validate-template --template-body file://$DIR/template.yaml
          cfn-lint -I $DIR/template.yaml
        done
  scans:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Terrascan scan
      continue-on-error: true
      uses: tenable/terrascan-action@main
      with:
        iac_type: cft
    - name: Checkov scan
      continue-on-error: true
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli
        output_file_path: console

