name: Deploy resource using Cloudformation stacks

on: push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  check:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
    - name: Chekout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install awscli cfn-lint
    - name: Validate & lint template
      run: |
        ls -laht
        git config --local user.email github-actions
        git config --local user.name github-actions@github.com
        git status


