name: Deploy resource using Cloudformation stacks

on: push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install awscli cfn-lint
    - name: Validate & lint template
      run: |
        ls -laht
        git status
        git diff $GITHUB_REF_NAME~1 $GITHUB_REF_NAME


